#!/bin/sh

case $BLOCK_BUTTON in
    1) notify-send "$(acpi -b)";;
    3) notify-send "$(acpi -i)";;
esac

# Loop through all attached batteries.
for battery in /sys/class/power_supply/BAT?*; do
    # If non-first battery, print a space separator.
    [ -n "${capacity+x}" ] && printf " "

    # Sets up the status and capacity
    case "$(cat "$battery/status")" in
        "Full") status="" ;;
        "Discharging") status="" ;;
        "Charging") status="🔌" ;;
        "Not charging") status="" ;;
        "Unknown") status="♻️" ;;
    esac
    capacity=$(cat "$battery/capacity")

    # Will make a warn icon if discharging and low
    [ "$capacity" -le 50 ] && [ "$status" != "🔌" ] && status=""
    [ "$capacity" -le 25 ] && [ "$status" != "🔌" ] && status=""

    # Output battery info
    printf "%s" "$status $capacity%" 
done && exit 0
