#!/bin/sh

# Loop through all attached batteries.
for battery in /sys/class/power_supply/BAT?*; do
    # If non-first battery, print a space separator.
    [ -n "${capacity+x}" ] && printf " "

    # Sets up the status and capacity
    case "$(cat "$battery/status")" in
            "Full") status="⚡" ;;
            "Discharging") status="" ;;
            "Charging") status="⚡" ;;
            "Not charging") status="" ;;
            "Unknown") status="♻️" ;;
    esac
    capacity=$(cat "$battery/capacity")

    # Will make a warn variable if discharging and low
    [ "$capacity" -le 50 ] && [ "$status" != "⚡" ] && status="❗" && notify-send -u normal "HALF BATTERY"
    [ "$capacity" -le 35 ] && [ "$status" != "⚡" ] && status="❗" && notify-send -u critical "LOW BATTERY"

    # Output battery info
    echo " $status$capacity%" 
done && exit 0
