#!/bin/sh

case $BLOCK_BUTTON in
	1) setsid "$TERMINAL" -e bluetoothctl & ;;
esac

status="$(echo -e 'info' | bluetoothctl | awk '/Name:/ {printf $2}')"
[ -z "$status" ] && echo " 0" 
echo " $status"
