#!/bin/sh

case $BLOCK_BUTTON in
	1) setsid "$TERMINAL" -e nmtui & ;;
esac

grep -q "down" /sys/class/net/w*/operstate && wifiicon="" ||
	wifiicon="$(grep "^\s*w" /proc/net/wireless | awk '{ print "",int($3 * 100 / 70) "%" }')"
ping -q -c 1 -w 1 1.1.1.1 > /dev/null || wifiicon=""
printf " %s" "$wifiicon"
