#!/bin/sh

case $BLOCK_BUTTON in
    1) setsid -f "$TERMINAL" -e nmtui ;;
    2) wifi_selector ;;
esac

#grep -q "down" /sys/class/net/w*/operstate && wifiicon="" ||
    #wifiicon="$(grep "^\s*w" /proc/net/wireless | awk '{ print "",int($3 * 100 / 70) "%" }')"
#ping -q -c 1 -w 1 1.1.1.1 > /dev/null || wifiicon=""
#printf " %s" "$wifiicon"
if grep -xq 'up' /sys/class/net/w*/operstate 2>/dev/null ; then
    wifiicon="$(awk '/^\s*w/ { print "📶", int($3 * 100 / 70) "% " }' /proc/net/wireless)"
elif grep -xq 'down' /sys/class/net/w*/operstate 2>/dev/null ; then
    grep -xq '0x1003' /sys/class/net/w*/flags && wifiicon="📡 " || wifiicon=" "
fi

printf " %s" "$wifiicon"
