#!/bin/sh

case $BLOCK_BUTTON in
    1) setsid -f "$TERMINAL" -e neomutt ;;
    3) notify-send "Syncing mails..." && setsid mailsync >/dev/null ;;
esac

unread="$(find "${XDG_DATA_HOME:-$HOME/.local/share}"/mail/*/[Ii][Nn][Bb][Oo][Xx]/new/* -type f | wc -l 2>/dev/null)"
echo " $unread"
