#!/bin/sh

case $BLOCK_BUTTON in
    1) notify-send "$(acpi -b)";;
    3) notify-send "$(acpi -i)";;
esac

PCT=0
IS_CHARGING=0
output=""

# Loop through all attached batteries.
for battery in /sys/class/power_supply/BAT?*; do
    # Sets up the status and capacity
    case "$(cat "$battery/status")" in
        "Full") status="" ;;
        "Discharging") status="" ;;
        "Charging") status="🔌" ;;
        "Not charging") status="" ;;
        "Unknown") status="♻️" ;;
    esac
    capacity=$(cat "$battery/capacity")

    # Will make a low battery icon if discharging and low
    [ "$capacity" -le 50 ] && [ "$status" != "🔌" ] && status=""
    [ "$capacity" -le 25 ] && [ "$status" != "🔌" ] && status=""

    # Output battery info
    #printf "%s" "$status $capacity%" 

    # Concatenate batteries' info
    output="${output}$status $capacity% "

    # Calculate total battery percentage
    PCT=`expr $PCT + $capacity`

    # TODO check charging status more elegantly
    [ "$status" == "🔌" ] && [ "$IS_CHARGING" != 1 ] && IS_CHARGING=1
done

# Send notify if total battery percentage < 20
[ "$IS_CHARGING" != 1 ] && [ "$PCT" -le 20 ] && notify-send -u critical "!!! LOW BATTERY !!!"

# Output battery info, trim leading and trailing white spaces
echo "$output" | awk '{$1=$1};1'
