#!/bin/sh

case $BLOCK_BUTTON in
    1) notify-send " Usage" "\- Middle click to open terminal.\n- Right click to restart dwmblocks.\n- Super + Left click to open system action menu.\n- Super + Middle click to restart dwm." ;;
    2) setsid -f "$TERMINAL";;
    3) kill -USR1 "$(pidof -s dwmblocks)" && notify-send -t 2000 "dwmblocks" "Restarted";;
    4) sysact;;
    5) kill -HUP "$(pidof -s dwm)" && notify-send -t 2000 "dwm" "Restarted";;
esac;
echo " " 
