#!/bin/sh
# Requires tpacpi-bat

if [ -n "$2" ]; then
    bat=$1
    end=$2
    start=$((end - 1))
else
    bat=0
    end=80
    start=79
fi
tpacpi-bat -s start $bat ${start:-79} && tpacpi-bat -s stop $bat ${end:-80} && 
echo "BAT$bat - Charging to ${end:-80}"
