#!/bin/sh

case $BLOCK_BUTTON in
	1) setsid "$TERMINAL" -e neomutt & ;;
	2) setsid mailsync >/dev/null & ;;
esac

unread="$(find "${XDG_DATA_HOME:-$HOME/.local/share}"/mail/*/[Ii][Nn][Bb][Oo][Xx]/new/* -type f | wc -l 2>/dev/null)"

#icon="$(cat "/tmp/imapsyncicon_$USER" 2>/dev/null)"
#echo "📬 $unread"
echo " $unread"
