#!/bin/sh

case "$(printf "a selected area (clipboard)\\na selected area\\ncurrent window (clipboard)\\ncurrent window\\nfull screen (clipboard)\\nfull screen" | dmenu -l 6 -i -p "Screenshot which area?")" in
	"a selected area (clipboard)") maim -s | xclip -selection clipboard -t image/png ;;
	"a selected area") maim -s $HOME/pics/pic-selected-"$(date '+%y%m%d-%H%M-%S').png" ;;
	"current window (clipboard)") maim -i "$(xdotool getactivewindow)" | xclip -selection clipboard -t image/png ;;
	"current window") maim -i "$(xdotool getactivewindow)" $HOME/pics/pic-window-"$(date '+%y%m%d-%H%M-%S').png" ;;
	"full screen") maim $HOME/pics/pic-full-"$(date '+%y%m%d-%H%M-%S').png" ;;
	"full screen (clipboard)") maim | xclip -selection clipboard -t image/png ;;
esac
