#!/bin/sh

# A dmenu wrapper script for system functions.

cmds="\
nothing  :
lock     : slock
leave    : kill -TERM $(pidof -s dwm)
refresh  : kill -HUP $(pidof -s dwm)
reboot   : reboot
suspend  : systemctl suspend
poweroff : poweroff
"

choice="$(echo "$cmds" | cut -d ':' -f 1 | dmenu)"
`echo "$cmds" | grep "^$choice" | cut -d ':' -f2`
