#!/bin/sh

id=$(xinput list | sed '/Synaptics/s/.*id=\([0-9]*\).*/\1/;t;d')
enabled=$(xinput list-props "$id" | grep '\bDevice Enabled\b' | sed 's/.*\(.\)$/\1/')

if [ "$enabled" = 1 ]; then
    xinput disable "$id" && notify-send "Touchpad" "Disabled"
else
    xinput enable "$id" && notify-send "Touchpad" "Enabled"
fi
