#!/bin/sh

case $BLOCK_BUTTON in
        1) setsid "$TERMINAL" -e alsamixer & ;;
esac

# volstat="$(amixer get Master)" # ALSA only equivalent.
# vol=$(amixer get Master | awk -F"[][]" '/dB/ { print $2  }' | sed 's/%//')

volstat="$(pactl list sinks)"
echo "$volstat" | grep -q bluetooth && vol="$(echo "$volstat" | grep 'Volume: front-left:' | tac | sed "s,.* \([0-9]\+\)%.*,\1,;1q")" ||
    vol="$(echo "$volstat" | grep 'Volume: front-left:' | sed "s,.* \([0-9]\+\)%.*,\1,;1q")"

if [ "$vol" -gt "70" ]; then
        icon="🔊"
elif [ "$vol" -lt "20" ]; then
        icon=""
else
        icon=""
fi

#echo "$volstat" | grep -q "Mute: yes" && icon="🔇"
echo "$volstat" | grep "Mute:" | tail -n1 | grep -q "yes" && icon="🔇"
printf "%s %s%%\\n" "$icon" "$vol"
