#!/bin/bash

prompt="Add a task: "
task=$(dmenu -p "$prompt" </dev/null)
prompt="Send notification in (minute): "
time=$(dmenu -p "$prompt" </dev/null)
notify-send "Reminding '$task' in ${time}m"
sleep "$time"m && notify-send -u critical "$task"
