#!/bin/sh

case $BLOCK_BUTTON in
	1) notify-send "🖥 CPU hogs" "$(ps axch -o cmd:15,%cpu --sort=-%cpu | head)\\n(100% per core)" ;;
	2) setsid "$TERMINAL" -e htop & ;;
esac

#(grep 'cpu ' /proc/stat; sleep 0.1; grep 'cpu ' /proc/stat) | awk -v RS="" '{ print ""($13-$2+$15-$4)*100/($13-$2+$15-$4+$16-$5)"%"}'

lscpu | awk '/^CPU MHz/ {printf "%.2fGHz", $3 / 1000}'
