#!/bin/sh

case $BLOCK_BUTTON in
    1) toggle_lang; kill -44 $(pidof dwmblocks);;
esac

if [ "$(ibus engine)" = "Bamboo"  ]; then
    LANG="VN"
else
    LANG="EN"
fi

#printf "%s" "$LANG"
echo $LANG
