#!/bin/sh
# This script is called on startup to remap keys.

setxkbmap us
# Increase key speed via a rate change
xset r rate 300 20
# Map the caps lock key to super...
setxkbmap -option caps:super
# But when it is pressed only once, treat it as escape.
killall xcape 2>/dev/null ; xcape -t 200 -e 'Super_L=Escape'
