#!/bin/sh

# A dmenu wrapper script for system functions.

cmds="\
lock     : slock
leave    : kill -TERM $(pidof -s dwm)
refresh  : kill -HUP $(pidof -s dwm)
reboot   : sudo -A reboot
poweroff : poweroff
"

#shutdown : sudo -A shutdown -h now

choice="$(echo "$cmds" | cut -d ':' -f 1 | dmenu)"
`echo "$cmds" | grep "^$choice" | cut -d ':' -f2`
